language:       cpp
compiler:
              - gcc
              - clang
before_install:
              - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
              - sudo apt-get -qq update
install:
              - if [[ "$CXX" = "g++" ]]; then
              -   sudo apt-get -qq install gcc-4.8 g++-4.8
              -   export CXX="g++-4.8" CC="gcc-4.8"
              - fi
script:         scons
notifications:
  email:
    on_success: never
    on_failure: never
